version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "pizzaDB"
      POSTGRES_USER: "pizzaRoot"
      POSTGRES_PASSWORD: "pizzaRootPass"
    ports:
      - "5432:5432"
